version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies and set path
          command: |
            # Need hdf5 and gsl-dev for msprime. When we move to tskit we should 
            # be able to remove these.
            sudo apt-get install libcap-dev libnuma-dev libhdf5-dev libgsl-dev
            pip install --user -r requirements/development.txt
            echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Compile Python
          command: |
            CFLAGS=--coverage python setup.py build_ext --inplace
      - run:
          name: Lint Python
          command: |
            flake8 --max-line-length 89 tsinfer setup.py tests
      - run:
          name: Run Python tests 
          command: |
            nosetests -v --with-coverage --cover-package tsinfer \
              --cover-branches --cover-erase --cover-xml \
              --cover-inclusive python/tests
            # python3 -m codecov -F python
