name: lint

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint-c:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: install clang-format
      run: |
        sudo apt-get remove -y clang-6.0 libclang-common-6.0-dev libclang1-6.0 libllvm6.0
        sudo apt-get autoremove
        sudo apt-get install clang-format clang-format-6.0
    - name: install run-clang-format
      run: wget https://raw.githubusercontent.com/Sarcasm/run-clang-format/de6e8ca07d171a7f378d379ff252a00f2905e81d/run-clang-format.py
    # The exlude patterns for -r is pretty weak, and we can't use shell globbing here.
    # Also we can't split this across multiple lines as the whitespace ends up being
    # significant. Sigh.
    - name: clang-format
      run: python run-clang-format.py --clang-format-executable=clang-format lib/ancestor_matcher.c lib/ancestor_builder.c lib/err.h lib/object_heap.c lib/object_heap.h lib/tree_sequence_builder.c lib/tsinfer.h lib/tests/tests.c
  pre-commit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
